// react/my-app/src/components/Tab.tsx
import "./Tab.css";
import React, { useState } from "react";

export interface TabProps {
    content: {
        title: string
        text: string
    }[];
    tabTitle: string;
}

export function Tab({ content, tabTitle }: TabProps) {
  const [currentOption, setCurrentOption] = useState(0);

  function select(optionIndex: number) {
    setCurrentOption(optionIndex);
  }

  const buttons = content.map((obj, index) => (
    <button
      key={obj.title}
      className={index === currentOption ? "selected" : ""}
      onClick={() => select(index)}
    >
      {obj.title}
    </button>
  ));

  const tabMode = (
    <div className="tabPane">
      <div> <h1> {tabTitle} </h1> </div>
      {buttons}
      <div className="textPane"> {content[currentOption].text} </div>
    </div>
  );

  return <div className="tabPane">{tabMode}</div>;
}

// vue/tab/src/stories/Tab.vue
<template>
  <div className="tabPane">
    <div> 
    <h1> {{ tabTitle }}</h1>
    </div>
    <button
      v-for="(option, index) in content"
      :key="option"
      :class="{ selected: index === currentOption }"
      @click="select(index)"
    >
      {{ option['title'] }}
    </button>
    <div>
      <Option v-bind="content[currentOption]" />
    </div>
  </div>
</template>

<script setup lang="ts">
import {ref} from 'vue';
import Option, { type OptionProps } from './Option.vue';

export interface TabProps {
  content: {
    title: string;
    text: string;
  }[];
  tabTitle: string;
}

// definindo as propriedades
defineProps<TabProps>();

const currentOption = ref(0); // armazena qual é a Opção selecionada no momento.

/** Atualiza a opção selecionada pelo usuário. */
function select(optionIndex: number) {
  currentOption.value = optionIndex;
}
</script>

<style>
.tabPane {
  padding: 50px;
  text-align: center
}

button {
  margin: 0px 17px 10px 17px;
  background-color: #eee;
  border: 2px solid rgb(118, 118, 118);
  border-radius: 3px;
  padding: 5px 30px;
}

.selected {
  font-weight: bold;
  background-color: #aaa;
}
</style>
