// react/my-app/src/components/Tab.tsx
import "./Tab.css";
import React, { useState } from "react";

export interface TabProps {
    content: {
        title: string
        text: string
    }[];
    tabTitle: string;
}

export function Tab({ content, tabTitle }: TabProps) {
  const [currentOption, setCurrentOption] = useState(0);

  function select(optionIndex: number) {
    setCurrentOption(optionIndex);
  }

  const buttons = content.map((obj, index) => (
    <button
      key={obj.title}
      className={index === currentOption ? "selected" : ""}
      onClick={() => select(index)}
    >
      {obj.title}
    </button>
  ));

  const tabMode = (
    <div className="tabPane">
      <div> <h1> {tabTitle} </h1> </div>
      {buttons}
      <div className="textPane"> {content[currentOption].text} </div>
    </div>
  );

  return <div className="tabPane">{tabMode}</div>;
}

// angular/tab/src/stories/tab.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tab',
  template: `
  <div> 
    <h1> {{ tabTitle }}</h1>
  </div>
  <button *ngFor = "let tab of content; let i = index" 
  [ngClass]="{'selected' : i === currentTab}"
  (click)="selected(i)
  "  
  >{{ tab.title }} </button>
  <div class="textPane">
    <h2 >{{ content[currentTab].text }}</h2>
</div>
  `,
  styleUrls: ['./tab.component.css'],
})

export default class TabComponent {

  // Definindo as entradas
  @Input() 
  content!: {title: string, text: string}[];

  @Input()
  tabTitle!: string;

  // Variaveis
  private currentTab = 0;

  // Função para atualizar o número que representa a Tab atual
  selected(optionIndex: number) {
    this.currentTab = optionIndex;
    console.log(this.currentTab);
  }
}
